version: "3.7"
services:
  postgres_TesteDev:
    container_name: postgres_teste-dev
    image: postgres:13.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"